function(anvil_enable_sanitizers target)
    if(MSVC)
        if(ANVIL_ENABLE_ASAN)
            target_compile_options(${target} INTERFACE /fsanitize=address)
            target_link_options(${target} INTERFACE /fsanitize=address)
        endif()
        if(ANVIL_ENABLE_UBSAN)
            message(WARNING "UndefinedBehaviorSanitizer is not available with MSVC")
        endif()
        return()
    endif()

    set(sanitizers "")
    if(ANVIL_ENABLE_ASAN)
        list(APPEND sanitizers "address")
    endif()
    if(ANVIL_ENABLE_UBSAN)
        list(APPEND sanitizers "undefined")
    endif()

    if(sanitizers)
        list(JOIN sanitizers "," sanitizer_list)
        target_compile_options(${target} INTERFACE -fsanitize=${sanitizer_list} -fno-omit-frame-pointer)
        target_link_options(${target} INTERFACE -fsanitize=${sanitizer_list})
    endif()
endfunction()
